In [2]:
# https://stackoverflow.com/questions/43599018/is-there-a-way-to-get-matplotlib-path-contains-points-to-be-inclusive-of-boundar
#I do quite like this command in Jupiter notebook:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))
#It makes things wider and not waste the space on your screen
import pandas as pd
import importlib
import csv,os
import numpy as np
import pandas as pd
import itertools
from uafgi import ioutil,shputil
from uafgi.data import greenland
import pyproj
import shapely
import copy
from uafgi import gicollections

#pd.set_option('display.max_rows', 30)

In [3]:
import uafgi.data.wkt
map_wkt = uafgi.data.wkt.nsidc_ps_north

In [5]:
import uafgi.data.w21
uafgi.data.w21.read(map_wkt).df

/Users/eafischer2/spack/var/spack/environments/pismip6-catalina/.spack-env/view/lib/python3.7/site-packages/pandas/core/series.py:4485: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,w21_popular_name,w21_greenlandic_name,w21_coast,w21_category,w21_Qr,w21_Qf,w21_Qm,w21_Qs,w21_Qc_inferred,w21_qm,...,w21_mean_undercutting_1992_1997,w21_mean_undercutting_1998_2007,w21_mean_undercutting_2008_2017,w21_mean_undercutting_uncertainty,w21_flux_basin_mouginot_2019,w21_mean_discharge,w21_mean_mass_balance,w21_reference_smb_1961_1990,w21_key,w21_allnames
0,Inngia Isbrae,Salliarutsip Sermia,CW,DW,9.00,8.54,0.73,0.00,16.81,0.53,...,0.50,0.80,0.45,41.07,INNGIA_ISBRAE,0.50,-0.6,0.2,"(Inngia Isbrae, INNGIA_ISBRAE)","(Inngia Isbrae, Salliarutsip Sermia)"
1,Umiammakku Isbrae,Umiammakku Sermiat,CW,DW,3.84,8.49,4.59,0.65,7.09,0.52,...,0.50,1.08,1.20,24.34,UMIAMMAKKU_ISBRAE,1.40,-0.8,0.8,"(Umiammakku Isbrae, UMIAMMAKKU_ISBRAE)","(Umiammakku Isbrae, Umiammakku Sermiat)"
2,Rink Isbrae,Kangilliup Sermia,CW,CR,1.19,1.08,4.11,0.20,NaN,NaN,...,1.13,1.56,1.78,22.13,RINK_ISBRAE,11.60,-0.4,11.6,"(Rink Isbrae, RINK_ISBRAE)","(Rink Isbrae, Kangilliup Sermia)"
3,Kangerlussuup Se.,Kangerlussuup Sermia,CW,CR,0.08,1.70,3.59,0.01,NaN,NaN,...,0.43,0.98,0.93,26.50,KANGERLUSSUUP_SERMERSUA,2.60,-0.9,2.2,"(Kangerlussuup Se., KANGERLUSSUUP_SERMERSUA)","(Kangerlussuup Se., Kangerlussuup Sermia)"
4,Kangerluarsuup Se.,Kangerluarsuup Sermia,CW,SC,1.10,-0.10,0.82,0.00,NaN,0.33,...,0.34,0.38,0.47,37.09,KANGERLUARSUUP_SERMIA,0.00,-0.2,0.0,"(Kangerluarsuup Se., KANGERLUARSUUP_SERMIA)","(Kangerluarsuup Se., Kangerluarsuup Sermia)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,Upernavik Isstrom NW,,NW,DW,5.34,2.05,0.37,2.47,4.55,1.01,...,1.03,1.26,0.88,19.35,UPERNAVIK_ISSTROM_N,2.52,-1.1,1.6,"(Upernavik Isstrom NW, UPERNAVIK_ISSTROM_N)","(Upernavik Isstrom NW, )"
222,Upernavik Isstrom N,,NW,DW,6.96,10.57,2.70,1.62,13.21,0.87,...,0.87,1.31,1.16,19.26,UPERNAVIK_ISSTROM_N,3.60,-1.5,2.2,"(Upernavik Isstrom N, UPERNAVIK_ISSTROM_N)","(Upernavik Isstrom N, )"
223,Upernavik Isstrom C,,NW,DW,3.89,4.65,3.09,1.33,4.12,0.85,...,0.85,1.25,1.27,19.38,UPERNAVIK_ISSTROM_C,4.70,-1.2,3.6,"(Upernavik Isstrom C, UPERNAVIK_ISSTROM_C)","(Upernavik Isstrom C, )"
224,Upernavik Isstrom S,Sermeq,NW,CR,1.14,0.34,3.02,0.00,NaN,NaN,...,0.64,1.09,1.03,21.35,UPERNAVIK_ISSTROM_S,2.80,-1.9,1.2,"(Upernavik Isstrom S, UPERNAVIK_ISSTROM_S)","(Upernavik Isstrom S, Sermeq)"
225,Upernavik Isstrom SS,,NW,SR,2.70,-0.63,NaN,0.00,NaN,NaN,...,0.39,0.74,1.04,22.08,UPERNAVIK_ISSTROM_SS,0.00,-0.8,-0.6,"(Upernavik Isstrom SS, UPERNAVIK_ISSTROM_SS)","(Upernavik Isstrom SS, )"

In [6]:
import uafgi.data.fj
uafgi.data.fj.read(map_wkt).df

    fj_fid                                            fj_poly  fj_key
0        0  POLYGON ((189251.1483580394 -868988.9774828344...       0
1        1  POLYGON ((-146117.4111413819 -859828.007851304...       1
2        2  POLYGON ((-587142.5312107351 -1169192.41485727...       2
3        3  POLYGON ((-482338.7741793855 -1235959.89245317...       3
4        4  POLYGON ((-447490.2261157235 -1417038.33912757...       4
5        5  POLYGON ((-384964.9177574713 -1464934.13934455...       5
6        6  POLYGON ((-378692.2106968834 -1504777.55780303...       6
7        7  POLYGON ((-320986.7050630721 -1724220.39495281...       7
8        8  POLYGON ((-216830.321290521 -2063046.486024775...       8
9        9  POLYGON ((-217681.8575036907 -2095200.78313045...       9
10      10  POLYGON ((-252302.8814601188 -2801660.78748833...      10
11      11  POLYGON ((-209597.8728502936 -3096738.12933800...      11
12      12  POLYGON ((-51895.27563101931 -3181517.42256358...      12
13      13  POLYGON ((108504.8167085364 -2949398.345986147...      13
14      14  POLYGON ((167764.800433395 -2724886.523235734,...      14
15      15  POLYGON ((353378.3932027738 -2572321.015126847...      15
16      16  POLYGON ((498198.5120069756 -2395971.815185406...      16
17      17  POLYGON ((547444.9131506938 -2316717.685679635...      17
18      18  POLYGON ((598469.6016746098 -2067935.494332621...      18
19      19  POLYGON ((553232.1652885491 -1884096.042851279...      19
20      20  POLYGON ((540675.7942563562 -1708105.800247232...      20
21      21  POLYGON ((543735.3962792035 -1657358.061285225...      21
22      22  POLYGON ((-313881.8767707587 -1843290.36289318...      22
23      23  POLYGON ((-313674.7039733952 -1839006.49013636...      23
24      24  POLYGON ((-313934.1396111443 -1839265.92577411...      24
25      25  POLYGON ((330594.1947652692 -2574830.622990893...      25
26      26  POLYGON ((509235.6167897159 -2315666.160952214...      26
27      27  POLYGON ((-246113.7592666132 -1988290.42498062...      27
28      28  POLYGON ((-222237.4080796503 -2127259.36721851...      28
29      29  POLYGON ((-210513.6907303631 -2264083.72701447...      29
30      30  POLYGON ((123747.171117389 -2927647.73993813, ...      30
31      31  POLYGON ((-198454.3335436573 -2174687.95710681...      31

In [4]:
import uafgi.data.m17
uafgi.data.m17.read(map_wkt).df

,m17_name,m17_lat,m17_lon,m17_speed,m17_drainage,m17_mc,m17_bathy,m17_ice_front_depth_b2013,m17_ice_front_depth_rtopo2,m17_ice_front_depth,m17_contconn300_b2013,m17_contcon300_rtopo2,m17_contcon300,m17_contconn200_b2013,m17_contcon200_rtopo2,m17_contcon200,m17_bathy_coverage,m17_loc,m17_key,m17_allnames
0,Jakobshavn Isbræ,69.158,-49.658,13255.0,90135.0,TW,1,1,-747.160,-851.1100,-814.910,1,1,0,1,1,1,POINT (-185314.9794306428 -2274444.822392135),"(Jakobshavn Isbræ, -49.658, 69.158)","(Jakobshavn Isbræ,)"
1,Kangerlussuaq Gletscher,68.609,-32.970,8141.0,95103.0,TW,1,0,-651.260,-676.1600,-901.110,1,0,1,1,0,1,POINT (488428.3323471585 -2291972.992205124),"(Kangerlussuaq Gletscher, -32.97, 68.609)","(Kangerlussuaq Gletscher,)"
2,Helheimgletscher,66.368,-38.213,7492.0,50023.0,TW,1,1,-832.510,-648.0300,-658.450,1,0,0,1,1,1,POINT (306726.2495522681 -2577257.151220952),"(Helheimgletscher, -38.213, 66.368)","(Helheimgletscher,)"
3,Køge Bugt C,65.170,-41.164,5240.0,18276.3,TW,1,0,-497.090,-278.5300,-328.140,0,0,0,0,0,1,POINT (182704.0390946306 -2724850.045440294),"(Køge Bugt C, -41.164, 65.17)","(Køge Bugt C,)"
4,Rink Isbræ,71.759,-51.606,4181.0,33171.0,TW,1,1,-849.780,-780.0400,-726.100,1,0,1,1,1,1,POINT (-229183.3083996871 -1978958.368034267),"(Rink Isbræ, -51.606, 71.759)","(Rink Isbræ,)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,Marie Gletscher,77.196,-66.087,11.0,3704.9,LT,0,0,140.630,28.9940,50.439,0,0,0,0,0,0,POINT (-501033.491227777 -1299336.341355892),"(Marie Gletscher, -66.087, 77.196)","(Marie Gletscher,)"
239,Kofoed-Hansen Bræ,77.528,-21.833,8.0,2230.9,LT,1,0,-110.370,-148.2700,-102.970,0,0,0,0,0,0,POINT (533547.1162769226 -1246841.512713166),"(Kofoed-Hansen Bræ, -21.833, 77.528)","(Kofoed-Hansen Bræ,)"
240,Newman Bugt,81.330,-57.287,7.0,301.0,LT,0,0,196.450,7.8675,22.741,0,0,0,0,0,0,POINT (-200236.3100095989 -919368.7919822223),"(Newman Bugt, -57.287, 81.33)","(Newman Bugt,)"
241,L. Bistrup Bræ,76.641,-22.696,6.0,24080.0,LT,0,0,-41.519,-90.9590,-125.540,0,0,0,0,0,0,POINT (551622.5562540012 -1344727.356947992),"(L. Bistrup Bræ, -22.696, 76.641)","(L. Bistrup Bræ,)"
242,Sermiarsupaluk (glacier),77.084,-66.222,5.0,506.9,LT,0,0,316.960,50.0300,51.763,0,0,0,0,0,0,POINT (-508538.9421344766 -1309599.974274568),"(Sermiarsupaluk (glacier), -66.222, 77.084)","(Sermiarsupaluk (glacier),)"

In [47]:
import select_glaciers
importlib.reload(select_glaciers)
over = greenland.read_overrides('overrides.ods', 'troughs/shp/terminus_locations.shp', ['w21_key', 'bkm15_key'], 'w21_key', greenland.map_wkt)
    
select = select_glaciers.select_glaciers_main()

===================================

In [10]:
select.df.columns

Index(['level_0', 'w21_popular_name', 'w21_greenlandic_name', 'w21_coast',
       'w21_category', 'w21_Qr', 'w21_Qf', 'w21_Qm', 'w21_Qs',
       'w21_Qc_inferred', 'w21_qm', 'w21_qf', 'w21_qc', 'w21_mean_depth',
       'w21_min_depth', 'w21_quality_str', 'w21_area_grounded_1992_2017',
       'w21_area_grounded_1992_1997', 'w21_area_grounded_1998_2007',
       'w21_area_grounded_2008_2017', 'w21_mean_fjord_width',
       'w21_length_grounded_1992_2017', 'w21_length_grounded_1992_1997',
       'w21_length_grounded_1998_2007', 'w21_length_grounded_2008_2017',
       'w21_ocean_model_sample_area', 'w21_mean_TF_1992-2017',
       'w21_mean_TF_1992-1997', 'w21_mean_TF_1998-2007',
       'w21_mean_TF_2008-2017', 'w21_subglacial_discharge_1992_2017',
       'w21_subglacial_discharge_1992_1997',
       'w21_subglacial_discharge_1998_2007',
       'w21_subglacial_discharge_2008_2017', 'w21_mean_xsection_area',
       'w21_mean_undercuttong_1992_2017', 'w21_mean_undercuttong_1992_1997',
       'w21_mean_undercuttong_1998_2007', 'w21_mean_undercuttong_2008_2017',
       'w21_mean_undercutting_uncertainty', 'w21_flux_basin_mouginot_2019',
       'w21_mean_discharge', 'w21_mean_mass_balance',
       'w21_reference_smb_1961_1990', 'w21_key', 'w21_allnames', 'include',
       'bkm15_key', 'bkm15_id', 'bkm15_new_greenl_name',
       'bkm15_old_greenl_name', 'bkm15_foreign_name', 'bkm15_official_name',
       'bkm15_alt', 'bkm15_allnames', 'lat', 'lon', 'loc', 'fj_poly',
       'ns481_key', 'ns481_grid', 'ns481_poly', 'cf20_key', 'cf20_glacier_id',
       'cf20_greenlandic_name', 'cf20_official_name', 'cf20_alt_name',
       'cf20_ref_name', 'cf20_fname', 'cf20_uniqename', 'cf20_locs',
       'cf20_allnames'],
      dtype='object')

In [35]:

selT = select.replace(df=select.df[~select.df['cf20_key'].isnull()])
selF = select.replace(df=select.df[select.df['cf20_key'].isnull()])

len(selF.df)

15

In [39]:
ns642 = greenland.read_ns642(greenland.map_wkt)
ns642x = greenland.ns642_by_glacier_id(ns642)
match = greenland.match_point_poly(ns642x, 'ns642_points', selF, 'fj_poly', right_cols=['lat','lon']).swap()
selF2 = match.left_join(overrides=over, right_cols=['ns642_GlacierID'])

In [43]:
selF.df[['w21_key','cf20_key']]

                                               w21_key cf20_key
index
1                              (F. Graae Gl., F_GRAAE)      NaN
2      (Deception O Gl. CN, UNNAMED_DECEPTION_O_CN_CS)      NaN
4                    (Perlerfiup Se., SERMEQ_SILARLEQ)      NaN
5               (Sermeq Avannarleq, SERMEQ_AVANNARLEQ)      NaN
10                  (Farquhar Gl., FARQUHAR_GLETSCHER)      NaN
14              (Kong Oscar Gl., KONG_OSCAR_GLETSCHER)      NaN
15                           (Morell Gl., GADE-MORELL)      NaN
16      (Nordenskiold Gl. N, NORDENSKIOLD_GLESCHER_NW)      NaN
17        (Upernavik Isstrom SS, UPERNAVIK_ISSTROM_SS)      NaN
18                              (Rimfaxe Gl., RIMFAXE)      NaN
19                      (Koge Bugt Gl. C, KOGE_BUGT_C)      NaN
26              (Jakobshavn Isbrae, JAKOBSHAVN_ISBRAE)      NaN
27                     (Helheim Gl., HELHEIMGLETSCHER)      NaN
30          (Upernavik Isstrom N, UPERNAVIK_ISSTROM_N)      NaN
31          (Upernavik Isstrom C, UPERNAVIK_ISSTROM_C)      NaN

In [45]:
cf20=greenland.read_cf20(greenland.map_wkt)
cf20.df

,cf20_glacier_id,cf20_greenlandic_name,cf20_official_name,cf20_alt_name,cf20_ref_name,cf20_fname,cf20_uniqename,cf20_locs,cf20_key,cf20_allnames
0,145,,Rosenborg Gletsjer,,Rosenborg Gletsjer,data/calfin/domain-termini/termini_1972-2019_R...,Rosenborg Gletsjer,"(POINT (660113.9263986081 -2273295.44275483), ...",Rosenborg Gletsjer,"(, Rosenborg Gletsjer, , Rosenborg Gletsjer)"
1,239,Akullikassaap Sermia,Akullikassaap Sermia,,Akullikassaap Sermia,data/calfin/domain-termini/termini_1972-2019_A...,Akullikassaap Sermia,"(POINT (-316662.1627268736 -1825438.86844664),...",Akullikassaap Sermia,"(Akullikassaap Sermia, Akullikassaap Sermia, ,..."
2,9,Sermeq Kujalleq,Sermeq Kujalleq,Store Gletsjer,Store Gletsjer,data/calfin/domain-termini/termini_1972-2019_S...,Store Gletsjer,(POINT (-209281.5987104931 -2135263.678403165)...,Store Gletsjer,"(Sermeq Kujalleq, Sermeq Kujalleq, Store Glets..."
3,7,Sermeq Kujalleq,Sermeq Kujalleq,Alianaatsup Sermia,Alianaatsup Sermia,data/calfin/domain-termini/termini_1972-2019_A...,Alianaatsup Sermia,(POINT (-200951.1578819107 -2178808.246109227)...,Alianaatsup Sermia,"(Sermeq Kujalleq, Sermeq Kujalleq, Alianaatsup..."
4,61,,Morell Gletsjer,Morell Gletsjer,Morell Gletsjer,data/calfin/domain-termini/termini_1972-2019_M...,Morell Gletsjer,(POINT (-450599.1160495596 -1424644.661579517)...,Morell Gletsjer,"(, Morell Gletsjer, Morell Gletsjer, Morell Gl..."
...,...,...,...,...,...,...,...,...,...,...
65,93,,Petermann Gletsjer,Petermann Gletscher,Petermann Gletsjer,data/calfin/domain-termini/termini_1972-2019_P...,Petermann Gletsjer,(POINT (-278050.4675527944 -921027.8792196793)...,Petermann Gletsjer,"(, Petermann Gletsjer, Petermann Gletscher, Pe..."
66,8,Sermeq Avannarleq,Sermeq Avannarleq,Sermeq Avangnardleq,Sermeq Avannarleq 70N,data/calfin/domain-termini/termini_1972-2019_S...,Sermeq Avannarleq 70N,(POINT (-203471.6745955368 -2172409.185260865)...,Sermeq Avannarleq 70N,"(Sermeq Avannarleq, Sermeq Avannarleq, Sermeq ..."
67,158,,Søndre Parallelgletsjer,,Sondre Parallelgletsjer,data/calfin/domain-termini/termini_1972-2019_S...,Sondre Parallelgletsjer,"(POINT (495203.8990325053 -2391731.428893349),...",Sondre Parallelgletsjer,"(, Søndre Parallelgletsjer, , Sondre Parallelg..."
68,175,,Helheim Gletsjer,,Helheim Gletsjer,data/calfin/domain-termini/termini_1972-2019_H...,Helheim Gletsjer,"(POINT (314419.4742228318 -2578108.668494095),...",Helheim Gletsjer,"(, Helheim Gletsjer, , Helheim Gletsjer)"
69,54,Issuusarsuit Sermiat,Issuusarsuit Sermiat,Peary Gletscher,Peary Gletscher,data/calfin/domain-termini/termini_1972-2019_P...,Peary Gletscher,"(POINT (-411384.7180210177 -1463461.65257702),...",Peary Gletscher,"(Issuusarsuit Sermiat, Issuusarsuit Sermiat, P..."

In [40]:
selF2.df[['w21_key','ns642_GlacierID']]

                                               w21_key  ns642_GlacierID
index
1                              (F. Graae Gl., F_GRAAE)              NaN
2      (Deception O Gl. CN, UNNAMED_DECEPTION_O_CN_CS)            118.0
4                    (Perlerfiup Se., SERMEQ_SILARLEQ)            159.0
5               (Sermeq Avannarleq, SERMEQ_AVANNARLEQ)              NaN
10                  (Farquhar Gl., FARQUHAR_GLETSCHER)             14.0
14              (Kong Oscar Gl., KONG_OSCAR_GLETSCHER)              NaN
15                           (Morell Gl., GADE-MORELL)              NaN
16      (Nordenskiold Gl. N, NORDENSKIOLD_GLESCHER_NW)              NaN
17        (Upernavik Isstrom SS, UPERNAVIK_ISSTROM_SS)              NaN
18                              (Rimfaxe Gl., RIMFAXE)              NaN
19                      (Koge Bugt Gl. C, KOGE_BUGT_C)             82.0
26              (Jakobshavn Isbrae, JAKOBSHAVN_ISBRAE)              NaN
27                     (Helheim Gl., HELHEIMGLETSCHER)              NaN
30          (Upernavik Isstrom N, UPERNAVIK_ISSTROM_N)              NaN
31          (Upernavik Isstrom C, UPERNAVIK_ISSTROM_C)             51.0